from django.conf.urls import url
from django.contrib.auth.views import password_reset, password_reset_done

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    #url(r'^discover/$', views.discover, name='discover'),
    #url(r'^discover/success/$', views.signup_success, name='signup_success'),
    url(r'^login/$', views.signin, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout', kwargs={'next_page': '/week1/'}),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^home/$', views.home, name='home'),
    #url(r'^edit/$', views.home_edit, name='homeedit'),
    url(r'^reset/$', views.reset, name='reset'),
    url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.reset_confirm, name='reset_confirm'),
    url(r'^welcome/$', views.welcome, name='welcome'),#temporary
    url(r'^step1/$', views.step1, name='step1'),
    url(r'^step2/$', views.step2, name='step2'),
    url(r'^step3/$', views.step3, name='step3'),
    url(r'^step4/$', views.step4, name='step4'),
    url(r'^step5/$', views.step5, name='step5'),
    url(r'^step6/$', views.step6, name='step6'),
    url(r'^step7/$', views.step7, name='step7'),
    url(r'^search/results/(?P<query>[\w ]+)/$', views.results_search, name='resultsfriends'),
    url(r'^talent/list/(?P<query>\w+)/$', views.talent_list, name='talent_list'),
    #url(r'^hatsoff/(?P<user2>\d+)/$', views.hatsoff, name='hatsoff'),
    url(r'^hatsoff/list/$', views.hatsoff_list, name='hatsoff_list'),
    url(r'^thanks/list/$', views.thanks_list, name='thanks_list'),
    url(r'^follow/list/$', views.follow_list, name='follow_list'),
    url(r'^messages/$', views.messages, name='messages'),
    url(r'^messages/(?P<uid>\d+)/$', views.private_message, name='private_message'),
    url(r'^profile/(?P<uid>\d+)/$', views.get_profile, name='get_profile'),
    url(r'^community/$', views.community, name='community'),
    url(r'^community/post/$', views.community_post, name='community_post'),
    url(r'^community/members/$', views.community_members, name='community_members'),
    url(r'^community/needs/you/$', views.community_needyou, name='community_needyou'),
    url(r'^collaborators/you/need/$', views.collaborators_you_need, name='collaborators_you_need'),
    url(r'^collaborators/need/you/$', views.collaborators_need_you, name='collaborators_need_you'),
    url(r'^project/management/$', views.project_management, name='project_management'),
    url(r'^notification/$', views.notification, name='notification'),
    url(r'^edit/personalinfomation/$', views.home_edit_personalinfo, name='edit_personalinfo'),
    url(r'^edit/funfact/$', views.home_edit_funfact, name='edit_funfact'),
    url(r'^edit/photo/$', views.home_edit_photo, name='edit_photo'),
    url(r'^edit/url/$', views.home_edit_url, name='edit_url'),
    url(r'^edit/profession/$', views.home_edit_profession, name='edit_profession'),
    url(r'^edit/skills/$', views.home_edit_professionskills, name='edit_professionskills'),
    url(r'^edit/previouswork/$', views.home_edit_newpreviouswork, name='edit_newpreviouswork'),
    url(r'^edit/previousworks/(?P<num>\d+)/$', views.home_edit_previouswork, name='edit_previouswork'),
    url(r'^edit/upcomingwork/$', views.home_edit_upcoming, name='edit_upcoming'),
    url(r'^folder/$', views.folder, name='folder'),
    url(r'^folder/list/(?P<user2>\d+)/$', views.add_folder, name='add_folder'),
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^messageboard/$', views.historyboard, name='historyboard'),
]
